### ISSUE TITLE
[DOC] - How to deploy Nebari on an existing Kubernetes cluster

### ISSUE THREAD

**Issue by pavithraes** [nebari-dev/nebari-docs#256] opened 2023-01-11 15:42 UTC
### Preliminary Checks

- [X] This issue is not a question, feature request, RFC, or anything other than a bug report. Please post those things in GitHub Discussions: https://github.com/nebari-dev/nebari/discussions

### Summary

Create a new how-to-guide. We can take relevant sections from: https://github.com/nebari-dev/nebari-docs/pull/113

### Steps to Resolve this Issue

1.
2.
3.
...

**Comment by kcpevey** [comment] 2023-01-24 17:09
This looks like a duplicate of https://github.com/nebari-dev/nebari-docs/issues/108

**Comment by pavithraes** [comment] 2023-01-31 11:54
Thanks for the cross-ref! 

#108 was the original issue, and we decided to narrow its scope to [this](https://github.com/nebari-dev/nebari-docs/issues/108#issuecomment-1378941964) to make it a "good-first-issue". The issue we're on (`#256`) can then track actually writing the how-to page. 

I think we can update the title in #108 to make this clear. :)

**Closed** 2023-05-03 09:08 UTC
Labels: type: enhancement 💅🏼, help wanted, area: documentation 📖, status: in progress 🏗, impact: medium 🟨, content: doc/how-to
